version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: courtiq_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/courtiq
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static

  celery_worker:
    build: ./backend
    container_name: courtiq_celery
    command: celery -A tasks.celery worker --loglevel=info
    depends_on:
      - backend
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/courtiq
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static

  frontend:
    build: ./frontend
    container_name: courtiq_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - backend

volumes:
  mongo_data:
    driver: local
